### ISSUE TITLE
INS Review: fitsutil

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#50]

**Comment by sean-lockwood** [comment]
Various outfiles (including `outfile_rice` and `outfile_gzip`) should write to a local directory.
```hdu.writeto('/eng/ssb/iraf_transition/test_data/empty.fits', overwrite=True)```

**Comment by sean-lockwood** [comment]
Old commented-out code should be removed:
```#cut_hdulist = hdulist[0:2] + hdulist[]```

**Comment by samanthalh** [comment]
In the fpack-rickpack GZIP example (In[3]), change the hdu_rice to hdu_gzip in line 7:

Current: hdulist_gzip = fits.HDUList([hdulist[0],hdu_rice])
Should be: hdulist_gzip = fits.HDUList([hdulist[0],hdu_gzip])

**Comment by samanthalh** [comment]
In the fxdelete-fxsplit-fxextract example, the second output (output_2) writes out something identical to the original fits file. The third extension is not removed like it states in the description.

**Comment by samanthalh** [comment]
In the fxdelete-fxsplit-fxextract example, fix typo of thrid (shown below) to third.

Current: Now save a new copy of the original file without that thrid extension

**Comment by jaymedina** [comment]
## fxdummyh

- `PermissionError: [Errno 13] Permission denied: '/eng/ssb/iraf_transition/test_data/empty.fits'` when trying to run the following line: 

`hdu.writeto('/eng/ssb/iraf_transition/test_data/empty.fits', overwrite=True)`

And it looks like permissions need to be changed if you want users to overwrite the `empty.fits` file. 

`-rw-r--r--  1 ogaz  STSCI\science   2.8K Dec  4 16:41 /eng/ssb/iraf_transition/test_data/empty.fits`

- It would be a good idea to have an example where you create an empty FITS file with more than one extension:
```
hdu1 = fits.PrimaryHDU()
hdu2 = fits.ImageHDU()
hdu3 = fits.ImageHDU()
list = fits.HDUList([hdu1, hdu2, hdu3])
list.writeto('empty.fits', overwrite=True)
```
## fxplf

`PermissionError: [Errno 13] Permission denied: '/eng/ssb/iraf_transition/test_data/table3.fits'` when trying to run the following line: 

`t.write(outfile, overwrite=True)`

Permissions:
`-rw-r--r--  1 ogaz  STSCI\science   8.4K Dec  4 16:41 /eng/ssb/iraf_transition/test_data/table3.fits`

## fxheader

- Typo: '... been replaced in a **convience** function ...' --> 'convenience'
- fxheader on IRAF does not display Cards, Dimensions, and Format. It would be a good idea to describe what those columns are to the users.

**Comment by SaOgaz** [comment]
@jaymedina, that's correct that you guys will not have write permissions on these files.  I wanted you guys to re-write the files locally for testing. It's something I need to address before we release the notebooks to the public in an "official" capacity.

**Comment by SaOgaz** [comment]
I've incorporated all fixes up to here.
