### ISSUE TITLE
INS Review: images.imfilter

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#51]

**Comment by mackjenn** [comment]
**median**
It would be helpful to show how to save the median smoothed array as a fits file. 
Also, what are the python equivalents of the IRAF parameters zloreject and zhireject?

**Comment by sean-lockwood** [comment]
**mode-rmode**:
- Make images larger with `set_size_inches()`

**Comment by SaOgaz** [comment]
@mackjenn, for the filters in astropy, there is a replacement for zloreject and zhireject.  Unfortunately, there's not an astropy median convolution.  Do you find yourself using median a lot?  Actually, which if any of the convolution functions do you use the most?  I will take that one and add an example with "zloreject" equivalent to that entry.

**Comment by SaOgaz** [comment]
I've incorporated all comments up to here, except for adding a zloreject example.

**Comment by SaOgaz** [comment]
Jen says: ring median

**Comment by mackjenn** [comment]
rmedian iby07phuq_flc.fits[1] iby07phuq_flc_rmed.fits rinner=5 router=10 zloreject=-99

**Comment by SaOgaz** [comment]
Add to top of notebook in notes section that an example using a zloreject and zhighreject is in the task rmedian

**Comment by SMBaggett** [comment]
**laplace**

- Thanks, example works as advertised. Tried running the same laplace filter with same boundary in python and in pyraf to see if output image agreed (it did not but perhaps parameters weren't identical).

**Comment by jaymedina** [comment]
## mode-rmode
- Providing a link to the `scipy.ndimage.generic_filter` function would be helpful for quick reference
- Maybe try creating a separate plot with the 2 subplots being:
1) The filtered image when using the `size` parameter
2) The filtered image when using the `footprint` parameter

It should be noted that using the `footprint` parameter will give you the same results as IRAF's `rmode`.
