### ISSUE TITLE
INS Review: images.imfit

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#52]

**Comment by SaOgaz** [comment]
Daniel Welty brought up what's probably a typo:

"The function z is defined as
z = 2. * x ** 2 - 0.5 * x ** 2 + 1.5 * x * y - 1.
 
Why the separate terms for x**2?  Should one have been for y**2?"

**Comment by tddesjardins** [comment]
**Feedback on images.imfit**
1) In the introduction at the top, remove the comma after Astropy in "Astropy, and Scipy."

*Under fit1d-lineclean:*

2) Note that the Legendre1D fitting example generates a warning.
"WARNING: Model is linear in parameters; consider using linear fitting methods. [astropy.modeling.fitting]

3) For the lineclean example, could add another comment under "Value Replacement - Spline 1" to be more explicit about what the example is supposed to do. I was a little confused at first. Maybe "This example shows how to remove outliers to achieve a better fit."

**Comment by SaOgaz** [comment]
@tddesjardins, I had talked to Larry about this warning a while ago and he told me it was kind of unavoidable here.  I could suppress warnings, but I'm hesitant to put that kind of thing in the notebook at all, thoughts?  Thanks for the review!

Incorporated all fixes up to here.

**Comment by tddesjardins** [comment]
No problem in that case, @SaraOgaz . I just wanted to make sure I documented it any time I encountered a warning or an error.
