### ISSUE TITLE
INS Review: images.imutil

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#54]

**Comment by SMBaggett** [comment]
imreplace
   - Could use couple of intermediate steps to illustrate action to the reader e.g.
         show small image section before & after replacement is done
   - Pointer to the 'dilation' is helpful but would put an example inside imreplace of how to do it

**Comment by tddesjardins** [comment]
**Feedback on images.imutil**

*Under chpixtype:*

1) Example produces a warning. "WARNING: AstropyDeprecationWarning: 'clobber' was deprecated in version 2.0 and will be removed in a future version. Use argument 'overwrite' instead. [__main__]". Suggest changing as the warning indicates and update the comment in the example telling the user to use the clobber argument.

*No comments for hedit.*

*Under hselect:*

2) Was asked to review this, but no content is in the notebook.

*Under imarith-imdivide:*

3) Comment text change: "using the shortcute += operator" -> "using the shortcut += operator"

4) Running the example produces a TypeError for this line:

hdu1[4].data[indx_nonzeros] /= hdu2[4].data[indx_nonzeros]

Error text: "ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'h') according to the casting rule ''same_kind''"

5) Should presumably also generate a warning about the clobber option. See (1) above.

*Under imcopy:*

6) In the second code block of the example, the comment mentions the clobber argument, but correctly uses the overwrite argument. Update the comment.

7) The cutout example says the output should be 100 x 100 pixels, but the command appears to be 50 x 50 pixels in the call to Cutout2D. 

8) The resulting cutout from Cutout2D does not seem to have the same WCS if I align the cutout and the original image with Match -> Frame -> WCS in DS9. The coordinate axes even seem to be different.

*Under imfunction-imexpr:*

9) Missing a period in the last sentence of the first paragraph ("...functionality of the numpy library").

*Under imheader:*

10) Incorrectly formatted print statement for Python 3.

11) I would suggest adding an example not using the convenience function, as sometimes you might want to grab data from multiple parts of a file with a single open statement without opening/closing repeatedly. So, add:

```
with fits.open(test_data[0]) as hdu:
     head = hdu[1].header
     print(repr(head))
```
	
or similar.

**Comment by SMBaggett** [comment]
**hedit** 

- Would add statement to hedit introduction: "To prevent inadvertent clobbering of keywords, use the fits.open 'readonly' option."
- Need example of how to update/insert keywords in more than 1 image at once.
- Include examples of how to simply view value of keyword(s) incl. wildcards e.g
```
In [45]: hdu[0].header['DETECTOR']
Out[45]: 'IR'
In [46]: hdu[0].header['DETECTOR'],hdu[0].header['FILTER'],hdu[0].header['EXPTIME']
Out[46]: ('IR', 'F140W', 602.937317)
In [47]: hdu[0].header['*PH*'] 
Out[47]:
PHOTCORR= 'COMPLETE'           / populate photometric header keywords
GRAPHTAB= 'N/A                    ' / the HST graph table
IMPHTTAB= 'iref$wbj1825ri_imp.fits' / Image Photometry Table
PHOTMODE= 'WFC3 IR F125W'      / observation con
PHOTFLAM=        2.2483417E-20 / inverse sensitivity, ergs/cm2/Ang/electron
PHOTFNU =        1.1692094E-07 / inverse sensitivity, Jy*sec/electron
PHOTZPT =       -2.1100000E+01 / ST magnitude zero point
PHOTPLAM=        1.2486060E+04 / Pivot wavelength (Angstroms)
PHOTBW  =        8.6628125E+02 / RMS bandwidth of filter plus detector
```
- Include example of how to view keywords from more than 1 image at once. This example with glob works but is there a better (shorter) way to do this?

```
In [37]: import glob
In [38]: from astropy.io import fits
In [39]: data = glob.glob('test_data/i*flt.fits')
In [40]: for filename in data:
    ...:     hdu = fits.open(filename, mode='update')
    ...:     imname = hdu[0].header['FILENAME']
    ...:     det = hdu[0].header['DETECTOR']
    ...:     print(imname,det)
    ...:
('iczgs3y5q_flt.fits', 'IR')
('iczgs3ygq_flt.fits', 'IR')
('iczgs3ygq_flt.fits', 'IR')

```

- How can the i_* keywords be accessed in python? They currently don't show up.
```
In [93]: hdu[0].header['i_*']
Out[93]:
But are visible in pyraf:
--> hedit test_data/iczgs3y5q_flt.fits[0] i_* .
test_data/iczgs3y5q_flt.fits[0],i_ctime = 1201980827
test_data/iczgs3y5q_flt.fits[0],i_history =
test_data/iczgs3y5q_flt.fits[0],i_limtime = 1201946880
test_data/iczgs3y5q_flt.fits[0],i_maxpixval = 0.
test_data/iczgs3y5q_flt.fits[0],i_minpixval = 0.
test_data/iczgs3y5q_flt.fits[0],i_mtime = 1201946881
test_data/iczgs3y5q_flt.fits[0],i_naxis = 0
test_data/iczgs3y5q_flt.fits[0],i_pixfile = test_data/iczgs3y5q_flt.fits
test_data/iczgs3y5q_flt.fits[0],i_pixtype = 3
test_data/iczgs3y5q_flt.fits[0],i_title =
```

**Comment by philhodge** [comment]
> How can the i_* keywords be accessed in python? They currently don't show up.

There are not literally any such keywords.  Those "keywords" are an iraf invention so that you use the same syntax for any image type (e.g. iraf format, stsdas format, FITS).  There is an iraf help file (I don't remember which, but I would first look at imheader) that describes these keywords.  For example, i_mtime is the modification time of the file (that's not usually any header keyword), and i_naxis is keyword NAXIS.

**Comment by SMBaggett** [comment]
Thanks for the suggestion, Phil. So sounds like these are unlikely to be used by observers? Here's what the helpfile had for them:
```
2.1 Standard header fields

        The  header editor may be used to access both the standard image
    header fields and any  user  or  application  defined  fields.   The
    standard  header fields currently defined are shown below.  There is
    no guarantee that the names and/or usage of these  fields  will  not
    change in the future.


            i_ctime         int             create time
            i_history       string          history comments
            i_limtime       int             time when min,max last updated
            i_maxpixval     real            maximum pixel value
            i_minpixval     real            minimum pixel value
            i_mtime         int             time of last modify
            i_naxis         int             number of axes (dimensionality)
            i_naxis[1-7]    int             length of each axis
            i_pixfile       string          pathname of pixel storage file
            i_pixtype       int             pixel datatype code
            i_title         string          title string


    The  standard  header  field names have an "i_" prefix to reduce the
    possibility of a name collision with  a  user  field  name,  and  to
    distinguish  the two classes of parameters in templates.  The prefix
    may be omitted provided the simple name is unique.

```

**Comment by sean-lockwood** [comment]
**hedit**:
- Fix double-negative: "# Simple header change, will add keyword if it doesn't not exist"

**imarith-imdivide**:
- When run in Python3, I get an error:
```TypeError                                 Traceback (most recent call last)
<ipython-input-3-2b6575784a61> in <module>()
     17 # Set this value as you would the divzero parameter in imarith
     18 set_zeros = 999.9
---> 19 hdu1[4].data[indx_nonzeros] /= hdu2[4].data[indx_nonzeros]
     20 hdu1[4].data[indx_zeros] = 999.9
     21 

TypeError: No loop matching the specified signature and casting
was found for ufunc true_divide
```
ext=4 is of type `int16`, so the integer division `//=` operator works, if that is intended.

**imfunction-imexpr**:
- Change name of function `vcos` to something more self-documenting.

**imreplace**:
- Mention what imreplace dos in text.

**imslice**:
- `clobber` --> `overwrite`
- `np.split` leaves a sparse dimension.  Perhaps use `.sqeeze()`?

**imstack**:
- \# Pull two image data arrays and **an** image header

**imsum**:
- `ccdproc` is not a library built into Astroconda.  Emphasize that it will need to be installed.

**listpixels**:
- FITs --> FITS

**Comment by jaymedina** [comment]
## imslice 
- Add `import numpy as np` in first cell
- Would suggest displaying what the shape of the image was before using `np.split`, in other words adding: 
`image1.shape`

## imsum
- Need a description of what imsum does
- Typo: 'Our **acutal** unit is electrons/sec...' --> 'actual'
- Last line of second cell: `print final_combine.data` 
   If users are using v3.5 it should be `print(final_combine.data)`
   The same correction should be done for imstatistics and listpixels

## listpixels
- Typos:
      >> 'indexs' --> 'indexes' 
      >> 'To quickly pull out the data array you can use the astropy **convience fucntion**' --> 'convenience' 'function' 
      >> 'Now we can index the array as desired **,** we're cutting out 5 in y, and 2 in x' --> period between **desired** and **we're**

**Comment by SaOgaz** [comment]
@SMBaggett, I believe Phil is correct, these keywords are not ones users will be accessing outside of IRAF.

**Comment by mackjenn** [comment]
**imstat:**

sigma_clipped_stats doesn't quite provide the same functionality as imstat

For example: 
imstat *flc.fits[1]           
               IMAGE      NPIX      MEAN    STDDEV       MIN       MAX
 iby001qzq_flc.fits[1]   8400896     58.83     596.5    -938.4    89563.

To get this, I used:

from astropy.io import fits
import numpy as np

data_flc='iby001qzq_flc.fits'
sci1_flc=fits.getdata(data_flc,ext=1)

flc_npix=len(sci1_flc.ravel())
flc_mean=np.mean(sci1_flc)
flc_std=np.std(sci1_flc)
flc_median=np.median(sci1_flc)
flc_min=np.min(sci1_flc)
flc_max=np.max(sci1_flc)
print('IMAGE         NPIX    MEAN    STDDEV    MEDIAN     MIN     MAX')
print(data_flc,flc_npix,flc_mean,flc_std,flc_median,flc_min,flc_max)

Returns: 
IMAGE      NPIX    MEAN    STDDEV    MEDIAN     MIN     MAX
iby001qzq_flc.fits 8400896 58.8315 596.464 36.3874 -938.449 89563.2

------------------------------
Second example:  How many pixels in the fits array are greater than a value of 10000?

imstat *flc.fits[1] lo=10000 fields=image,npix
               IMAGE      NPIX
 iby001qzq_flc.fits[1]   1106

Python equivalent:

data_flc='iby001qzq_flc.fits'
sci1_flc=fits.getdata(data_flc,ext=1)
w=np.where(sci1_flc > 10000.)
flc_npix=len(sci1_flc[w].ravel())
print('IMAGE,NPIX ',data_flc,flc_npix)

Returns:
IMAGE,NPIX  iby001qzq_flc.fits 1106

**Comment by SMBaggett** [comment]
**listpix**

- images.imutil typo: "arithimetic" should be "arithmetic"
- clicking on names at top of imutils page e.g. hedit, hselect does not position reader at that section

- listpix intro: very helpful to have that reminder there of differences in indexing between python & pyraf.
      Would even put those 2 key characteristics in bold: index starts with 0 (like IDL) and y-axis is first dimension.  Would mention that the zero-indexing does not apply to extension numbers.

- If there is a shorthand way in python to access extensions e.g. [SCI,3], [DQ,5], please include an example
- Could example be given on how to do listpix on wildcard list of files (i.e.  listpix i*fits[1][100,100])

**Comment by SMBaggett** [comment]
**imstack**

- Could use some explanation about 3-D images .. when python writes out the [4,1014,1014] image, it appears in pyraf as 1014,1014,4:
```
In [160]: print(outstack.shape)
(4, 1014, 1014)

--> catfits imstack_out.fits
EXT#  FITSNAME      FILENAME              EXTVE DIMENS       BITPI OBJECT
0     imstack_out.f                             1014x1014x4  -32
```

- Example in imstack notebook works fine as well as a riffs on that example..

**Comment by SMBaggett** [comment]
**imheader** 

Thanks; example in the notebook was helpful. Is there a way to refine it further e.g. dig out just certain keywords as piping iraf through grep would do?
```

-> imhead iab*fits[1] l+ | grep EXPTIME
EXPTIME =          2802.936035 / exposure duration (seconds)--calculated
EXPTIME =          2802.936035 / exposure duration (seconds)--calculated
EXPTIME =          2802.936035 / exposure duration (seconds)--calculated
EXPTIME =          2802.936035 / exposure duration (seconds)--calculated

test_data = glob.glob('test_data/iab*fits')
for filename in test_data:
     ...:     head = fits.getheader(filename,ext=1)
     ...:     print repr(head) | grep EXPTIME
  File "<ipython-input-276-27d41d970de3>", line 3
    print repr(head) | grep EXPTIME
                                  ^
SyntaxError: invalid syntax

```

**Comment by SMBaggett** [comment]
**magnify**

- typos in introduction:  iterpolation avaialable

- Reminder about python (y,x) format is helpful.

- Example works fine but could really use an example of magnifying a real fits image.

- call using zoom generates a warning:
```

In [82]: outarr = zoom(inarr, (0.5,2.5), order=0)
/Users/sbaggett/anaconda/lib/python2.7/site-packages/scipy/ndimage/interpolation.py:600: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)

Note: while warning says python2.7 is being used, I thought I had set up my environment to run the recommended python3:

(python3) sekhmet:test_data sbaggett$ which python
/Users/sbaggett/anaconda/envs/python3/bin/python
(python3) sekhmet:test_data sbaggett$ ipython
...
python3:In [13]: out_array = zoom(in_array, (0.5,2.5), order=0)
/Users/sbaggett/anaconda/lib/python2.7/site-packages/scipy/ndimage/interpolation.py:600: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)

This line added later: confirmed using version command as well:
(python3) sekhmet:test_data sbaggett$ python --version
Python 3.5.4




```

**Comment by mackjenn** [comment]
**imarith:**

'clobber' deprecated

Mention that the IRAF imarith only works on single extension files, thus creating an output of a single extension.
In this example, the output file has the same number of extensions as the input file.
imarith_out.fits
EXT#  FITSNAME      FILENAME              EXTVE DIMENS       BITPI OBJECT       
0     imarith_out.fits iczgs3ygq_flt.fits                       16                 
1       IMAGE        SCI                   1     1014x1014    -32                
2       IMAGE       ERR                   1     1014x1014    -32                
3       IMAGE       DQ                    1     1014x1014    16                 
4       IMAGE       SAMP               1     1014x1014    16                 
5       IMAGE       TIME                 1     1014x1014    -32                
6       BINTABLE    WCSCORR       1     24Fx7R

**Comment by mackjenn** [comment]
**imreplace:**

To complete the example, it would be useful to write a new fits file with the mask in place.

**Comment by SaOgaz** [comment]
In response to @mackjenn's comment about imarith, it was decided at the tag-up meeting to do the following:
Change the current example to package output into a new HDUList that just contains a primary header and the added science array.
Add a second example that does re-save out the first input file after adding in a DQ array from a second file.  (@mackjenn was that how you mentioned using imarith in the meeing?)

**Comment by SMBaggett** [comment]
**imstat**

- stats.sigma is noticably slower than imstat, ~5x in short example tried here .. ~ 11 sec for 1 science extension in python vs ~2 sec in pyraf. Is there anyway to speed that up? It's going to add up quickly when analyzing large numbers of observations.

```

In [53]: %timeit stats.sigma_clipped_stats(id1,sigma=3,iters=3)
10.8 s ± 74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

--> date; imstat safe.ido995fhq_flt.fits[1] nclip=3 lsig=3 usig=3; date
Mon Feb 12 12:58:30 EST 2018
#               IMAGE      NPIX      MEAN    STDDEV       MIN       MAX     MIDPT
 safe.ido995fhq_flt.fits[1]   8175970     8.487     4.299    -15.03     33.35     8.044
Mon Feb 12 12:58:32 EST 2018
#   bunch of different runs, most are 2 sec, one was 1sec

```
- Would be extremely helpful if python imstat could also provide Number of Pixels going into the stats measurement as well as min/max. This would be ideal task to be made into function if possible.

- Difference between stats from python vs  pyraf sometimes of order 0.01-0.02% or more; normally that's for the clipped case but it's clipping done to same level (e.g. 3 upper/lower sigma x 3 iterations). Might there be a bug somewhere?
```

In [20]: stats.sigma_clipped_stats(sci1,sigma=3, iters=3)
#   mean   midpt    stddev
Out[20]: (0.019052482001967252, 0.018232709, 0.006221641467313459)
vs
--> imstat iabz06geq_flt.fits[1] nclip=3 lsig=3 usig=3
  #                 IMAGE      NPIX      MEAN    STDDEV       MIN       MAX     MIDPT 
iabz06geq_flt.fits[1]   1009404   0.01909  0.006331  -0.01993   0.06017   0.01808

--> print (0.019052482001967252/0.01909 )	 = 0.998034677945   clipped mean
--> print (0.01823270/0.01808)		   = 1.00844579646     clipped midpt
--> print (0.00622164146731345/0.006331)	    = 0.982726499339	  clipped stddev


```

**Comment by SMBaggett** [comment]
**imhist**

- Need apostrophe:   matplotlib's hist function

- Section does refer back to docs for scaling, bin sizes, etc but still should provide a several other examples
- Could use an explanatory sentence about the 'flatten' routine - is that just converting a 2D image into a 1D array? If so, that must mean plt.hist can not work directly on 2D?
- Need an example of plt.hist that does not require Jupyter notebook to run. This, e.g., saves figure to png file.
```
import matplotlib
matplotlib.use('Agg')               # must be before importing pylot/pylab
import matplotlib.pyplot as plt
fig = plt.figure()
plt.xlabel('pix value')
plt.ylabel('number')
#plt.title=('sample histogram')      # did not show up in png
#plt.axis=([0.5,1.5,0.,15000])	     # had no effect on histogram axes
n, obins, patches = plt.hist(sci1f,bins=100,range=(0,2))
fig.savefig('temp.png')
```

- The %matplotlib inline doesn't work in ipython -- is it only for Jupyter notebooks (then would state so)
```

In [24]: %matplotlib inline
---------------------------------------------------------------------------
UnknownBackend                            Traceback (most recent call last)
<ipython-input-24-9e3324102725> in <module>()
----> 1 get_ipython().run_line_magic('matplotlib', 'inline')

~/anaconda/envs/stak_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2093                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2094             with self.builtin_trap:
-> 2095                 result = fn(*args,**kwargs)
   2096             return result
   2097 

<decorator-gen-107> in matplotlib(self, line)

~/anaconda/envs/stak_env/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/anaconda/envs/stak_env/lib/python3.6/site-packages/IPython/core/magics/pylab.py in matplotlib(self, line)
     97             print("Available matplotlib backends: %s" % backends_list)
     98         else:
---> 99             gui, backend = self.shell.enable_matplotlib(args.gui)
    100             self._show_matplotlib_backend(args.gui, backend)
    101 

~/anaconda/envs/stak_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   2981         # Now we must activate the gui pylab wants to use, and fix %run to take
   2982         # plot updates into account
-> 2983         self.enable_gui(gui)
   2984         self.magics_manager.registry['ExecutionMagics'].default_runner = \
   2985             pt.mpl_runner(self.safe_execfile)

~/anaconda/envs/stak_env/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py in enable_gui(self, gui)
    499         if gui:
    500             self.active_eventloop, self._inputhook =\
--> 501                 get_inputhook_name_and_func(gui)
    502         else:
    503             self.active_eventloop = self._inputhook = None

~/anaconda/envs/stak_env/lib/python3.6/site-packages/IPython/terminal/pt_inputhooks/__init__.py in get_inputhook_name_and_func(gui)
     36 
     37     if gui not in backends:
---> 38         raise UnknownBackend(gui)
     39 
     40     if gui in aliases:

UnknownBackend: No event loop integration for 'inline'. Supported event loops are: qt, qt4, qt5, gtk, gtk2, gtk3, tk, wx, pyglet, glut, osx

```
```

**Comment by SaOgaz** [comment]
@tddesjardins, I'm not seeing any problems with the alignment for the cutout2D example in imcopy.  Are you sure you were comparing the cutout output to jcq505010_drz.fits?  When I double checked it I accidentally used the iczgs3ygg_flts.fits file from the upper code box the first time.

**Comment by SaOgaz** [comment]
Hi all, I wanted to leave a quick note here about running examples with in to out fits files, and looping over multiple files.  I've added a few more examples of these things to some of the tasks, but not all the ones requested.  I think once we have added a link at the top of all notebooks to the astropy fits primer page, it is the responsibility of the users to read through that content.  It would simply take too much time for me to add these things to all the notebook examples, and I would argue the main purpose of these notebooks is to clue users into what function calls with give them the array manipulation they want.  In a Python workflow, the in and out of the FITS file formatting is essentially window dressing.

**Comment by SaOgaz** [comment]
Incorporated all comments up to this point.  

@SMBaggett, will get back to you on the imstat time differences.  The small percentage difference in values is almost definitely due to rounding errors because of the language difference.  This is always un-avoidable when switching languages as they usually handle data types differently, not to mentioned CPU and architecture differences between machines.

**Comment by SMBaggett** [comment]
@SaraOgaz If it's machine differences, I would've expected percentage diffs of order 10-4 to 10-6 % not the 0.2% or higher.

**Comment by SMBaggett** [comment]
@SaraOgaz Re: including examples with in/out fits files, is there any room for negotiation? The notebooks would be truly useful if they have standalone fits examples. Maybe there's some compromise possible, maybe a generic example at the very top or if you construct one or two specific task examples with full in/out fits files and others of us willing could try to work out examples for the rest.

**Comment by SaOgaz** [comment]
comments from meeting with Jen, add to imheader, saving header to a text file.
