### ISSUE TITLE
INS Review: images.tv

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#55]

**Comment by mackjenn** [comment]
The example for displaying an image shows how do do it in DS9 or Ginga
http://imexam.readthedocs.io/en/latest/imexam/examples.html#basic-usage

But the example for tvmark only shows how to load a coordinate list in Ginga.
http://ginga.readthedocs.io/en/latest/manual/plugins_local/tvmark.html

How do you do it in DS9??

**Comment by SaOgaz** [comment]
Hey @mackjenn, I'm moved this request to the imexam repo: https://github.com/spacetelescope/imexam/issues/131
