### ISSUE TITLE
INS Review: stsdas.anlysis.fitting

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#59]

**Comment by tddesjardins** [comment]
*No comments on gfit1d-nfit1d-ngaussfit.*

See my comments on images.imfit.fit1d-lineclean.

**Comment by jaymedina** [comment]
## function
This tutorial refers to another tutorial in the Notebook. If it's possible, it would be nice to have a link to the other Notebook for easy navigation.

**Comment by SaOgaz** [comment]
@jaymedina I tried so hard to make that happen T.T  But with sphinx building the documentation automatically I couldn't find a way to do it.
