### ISSUE TITLE
INS Review: stsdas.analysis.statistics

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#60]

**Comment by samanthalh** [comment]
With respect to the coxhazard task, several places in the notebook, including the task title, has a typo. Fix "coxharzard" to "coxhazard".

**Comment by samanthalh** [comment]
In the coxhazard example, be more explicit that the link contains a useful example. 

Current: The lifelines package contains this fitter here.
Change: See an example of this fitter here in the lifelines package documentation.

**Comment by tddesjardins** [comment]
*Under bhkmethod:*

1) There is a typo in the code in the second print statement. The string suggests it is the p value, but you print the tau variable a second time in stead.

**Comment by rayalucas** [comment]
# buckleyjames-kmestimate

There is no code block to run at this page, but there is a link to http://lifelines.readthedocs.io/en/latest/Quickstart.html#kaplan-meier-and-nelson-aalen which has lots of examples and some code blocks which I presume one may be able to cut and paste into a new Jupyter notebook and run as Python code. It might be useful to have some more explanatory text here at the top level explaining that to the novice user.

**Comment by jaymedina** [comment]
## twosampt
- Would it be possible to an example for each of the tests that were linked (Ranksums, Wilcoxon, Man-Whitney)?

**Comment by SMBaggett** [comment]
**kolmov**

- statistics general Info: typo statictics

- No code examples, just pointers to scipy documentation on one-sided and two-sided:

https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.ksone.html#scipy.stats.ksone
https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.kstwobign.html#scipy.stats.kstwobign

**Comment by SMBaggett** [comment]
**spearman**

- Unfamiliar with Scmitt reference, could specific a reference be provided?

- Notebook has short example (which works fine in ipython) plus pointer to scipy document

https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.spearmanr.html#scipy.stats.spearmanr

**Comment by SaOgaz** [comment]
HI all, appreciate the feedback.  I will not be incorporating any of the comments to expand any examples as these tasks were not in high demand, and I believe are quite specialized.  Will expand specific tasks if we end up getting any user requests to do so.
