### ISSUE TITLE
INS Review: stadas.toolbox.headers

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#61]

**Comment by sean-lockwood** [comment]
**stfhistory**:
- Copy and modify a local copy of the FITS file
- Close *my_file*

**Comment by samanthalh** [comment]
Typo in the comments of stfhistory. Change "adds" to "add". 

Current: The stfhistory task will read history information from a text file and adds it to an image header.
Change to: The stfhistory task will read history information from a text file and **add** it to an image header.

**Comment by samanthalh** [comment]
In stfhistory: Current history_info.txt reads 

"This file was written by a Grue
On January 01, 2017"

Change to something more descriptive of the example, like, "This is example ASCII text for the stfhistory example in STAK Notebooks" or something like that.

**Comment by samanthalh** [comment]
This example is currently failing to add the lines in history_info.txt to the header as advertised. 

I ran the stfhistory code in a local jupyter notebook with the stfhist.fits copied over so that it is also local. I executed the stfhistory cells and then checked the stfhist header and did not find the inserted header lines. Not sure what the issue is.

**Comment by samanthalh** [comment]
The upreffile example is empty.

**Comment by SMBaggett** [comment]
**hdiff**

- intro typos
   change "hdiff task will take two FITS " to "hdiff task will difference two FITS "
   change "detais " to "details "

- Good test case in example; should be sufficient to have just this one.

**Comment by jaymedina** [comment]
## hdiff
- Is there a way to compare 2 different extensions from 2 different FITS files? i.e: 
`printdiff('fileA.fits', 'fileB.fits', 'sci', 2, 'sci', 1)` 

Where the extension [sci,2] from `fileA.fits` is being compared against [sci,1] from `fileB.fits`.
It might be useful for some users to have that feature.

**Comment by SaOgaz** [comment]
Hey @jaymedina, you can't do this with the printdiff task itself, but you can do it with Differs directly.  I feel like this falls under the "details on a more advanced differ result see... etc." note that's in this section.

**Comment by SaOgaz** [comment]
Included edits up to here.
