### ISSUE TITLE
INS Review: stsdas.toolbox.imgtools

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#62]

**Comment by jaymedina** [comment]
## iminsert

Code change suggestion:
```
# generate test arrays
my_array = np.random.rand(7,7)
ones = np.array(([1,1,1],[1,1,1],[1,1,1]))

# replace middle 3x3 square with ones
my_array[2:2+ones.shape[0],2:2+ones.shape[1]] = ones       #<--- code change

# Print result
print(my_array)
```
General suggestion:
I would also suggest possibly supplementing your example with a visual representation. In other words, something like this (but written more elegantly): 


```
# generate test arrays
my_array = np.random.rand(7,7)
ones = np.array(([1,1,1],[1,1,1],[1,1,1]))
plt.figure(1)
plt.imshow(my_array)

# replace middle 3x3 square with ones
my_array[2:2+ones.shape[0],2:2+ones.shape[1]] = ones

plt.figure(2)
plt.imshow(my_array)
```

**Comment by SaOgaz** [comment]
Request sent to me by Jen Mack to add the following example to incalc:

im1 = science array of the FLT image
im2 = DQ array of the FLT image
im3 = object mask, where 1=good and 0 is bad
 
Ouput image = original science array, but with pixels masked as zero where the DQ array is > 16384 or the object mask is zero
 
imcalc input='icsza1qaq_flt.fits[1],icsza1qaq_flt.fits[3],icsza1qaq_sci1_objmask.fits' output='icsza1qaq_sci1_finalmask.fits' equals=if im3 .eq. 0 then 0 else if im2 .ge. 16384 then 0 else im1`

**Comment by rayalucas** [comment]
# mkgauss
No stak Jupyter notebook here. Documentation links to a web page, http://photutils.readthedocs.io/en/stable/api/photutils.datasets.make_gaussian_sources.html , which says that the page does not yet exist when you go to it.

**Comment by rayalucas** [comment]
# pixlocate
No stak Jupyter notebook - just links to SciPy.org  numpy.where documentation page.

**Comment by rayalucas** [comment]
# rd2xy-xy2rd
No stak Jupyter notebook - simply links to Astropy.wcs documentation page.

**Comment by SaOgaz** [comment]
EDIT: nvm, I pasted the exact code you sent me, duh.  I've added this example to imarith (what imcalc points to)

@mackjenn, did I write down that imcalc example down incorrectly with regards to the use of the DQ array?  Do you find yourself doing a straight DQ flag > "value" comparison, or the picking out of specific flags that most IRAF tasks do.

**Comment by SaOgaz** [comment]
Incorporated all comments up to here.

**Comment by jaymedina** [comment]
# improject

- Suggestion: Creating a simple 2d example to demonstrate what the `axis` parameter changes, and how the image is projected can help put things into perspective for users. Example below 

```
my_array = np.zeroes((5,5))
my_array[0,:] = 1.

print(my_array)
```
```
Output:
[[ 1.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
```

```
new_array = np.average(my_array, axis=1)
print(new_array)
```
```
Output:
[ 1.  0.  0.  0.  0.]
```

So now the user knows that setting `axis=1` means taking the average of each row, and projecting it onto a single row. Similarly `axis=0` tells Python to take the average of each column.

**Comment by philhodge** [comment]
I'd like to suggest that you use non-square arrays or images for examples, because it will be much easier to see which axis is being averaged (for example).  It's also very useful for testing, to catch bugs such as axis lengths or loop indices being swapped.
