### ISSUE TITLE
INS Review: stsdas.toolbox.tools

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#64]

**Comment by jaymedina** [comment]
## base2dec-dec2base

Typo: 'The base2dec and dec2base tasks **transfrom** ...' 
Typo: '... Python contains built in functionality to **transfrom** integers to **octoal**, hexidecimal, and binary.'

transform*
octal*

**Comment by rayalucas** [comment]
# newredshift

Missing? I see a “?” symbol and nothing else there.

**Comment by rayalucas** [comment]
# tprecess

No code here, but link merely goes to documentation at http://docs.astropy.org/en/stable/coordinates/#transformation where there are lots of details. Which part covers what tprecess would do? Would have to read and figure it out as best one can, I guess. And I suppose you would need to start up your own new blank Jupyter notebook and cut and paste some code from the examples to see if they work properly. But it might be good to explain/give that suggestion at this top level to new users who visit these web pages before they just click to go to the documentation pages which just cover all sorts of precession-related things.

**Comment by SMBaggett** [comment]
**epoch/tepoch**

- No examples here at all, just link to time module docs. Could really use a few examples here. If it's too time-consuming for in-house experts to produce them, think what a significant hurdle it is for an inexperienced python user! Examples need not (could not) cover all the functionality of pyraf epoch but merely a few common ones to help jumpstart new users e.g.
```

"human" date   <--->  MJD, SMS

--> epoch in="Feb 16,2018 11:21am" printout=mjd,sms
MJD  58165.4729166667
SMS 2018.047 11:21:00.00000

--> epoch in="2018.047 11:21:00.00000" qual=sms printout=date,mjd
16 Feb 2018 11:21:00.00000            FRI
MJD  58165.4729166667
-->
--> epoch 58165.4729166667 qual=mjd printout=date,sms
16 Feb 2018 11:21:00.00001            FRI
SMS 2018.047 11:21:00.00001

```

- Note added later: thanks to Harish, here's a code snippet which will convert SMS format to MJD

```

from datetime import datetime
from astropy.time import Time

In [149]: sms = '2018.047 11:21:00'
In [150]: dfmt = '%Y.%j %H:%M:%S'
In [151]: d = datetime.strptime(sms, dfmt)
In [152]: d
Out[152]: datetime.datetime(2018, 2, 16, 11, 21)

In [153]: Time(d).mjd
Out[153]: 58165.472916666666

which agrees with the pyraf equivalent..
--> epoch '2018.047 11:21:00.00000' qual=sms pr=sms,date,mjd
16 Feb 2018 11:21:00.00000            FRI
MJD  58165.4729166667
SMS 2018.047 11:21:00.00000

Once 'd' is set up as above looks like there's also
In [26]: Time(d).iso
Out[26]: '2018-02-16 11:21:00.000'
In [27]: Time(d).isot
Out[27]: '2018-02-16T11:21:00.000'
In [28]: Time(d).decimalyear
Out[28]: 2018.1273230593608

(haven't been able to work out converting to format of say "Feb 16 2018 11:21:00")

**Comment by SMBaggett** [comment]
**ddiff**

- In intro do this, would add that the dirs being diff'd in this example are root (ie. the parameter in os.walk is the one to change to experiment with other dirs).

**Comment by SaOgaz** [comment]
Hi @SMBaggett, with regards to the tepoch module, it's more that this is SUCH a broad area, and the Astropy documentation for this is so well developed, that I would much prefer users to go to the Astropy documentation for their resource.  But I will run this decision by a few others to get some more opinions on it.

**Comment by SaOgaz** [comment]
Okay, discussed it with Erik and I did add an example of how to use Time with a Table example, since that isn't *as* well documented in Astropy.

**Comment by SaOgaz** [comment]
all comments up to here incorporated.
