### ISSUE TITLE
INS Review: utilities

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#67]

**Comment by SaOgaz** [comment]
Write your feedback here...

**Comment by SMBaggett** [comment]
- detab/entab/translit

Section points to appropriate docs that are useful but if feeling generous, could include a couple short very simple examples e.g. 

```

In [9]: s = "Instrument reports for WFC3 can be found at"
In [10]: s.replace("WFC3","ACS")
Out[10]: 'Instrument reports for ACS can be found at'

In [11]: s = 'Instrument reports for WFC3 are at \t'
In [12]: s.replace('\t','--->')
Out[12]: 'Instrument reports for WFC3 are at --->'

In [13]: s = 'INSTRUMENT REPORTS FOR WFC3 ARE AT '
In [14]: s.lower()
Out[14]: 'instrument reports for wfc3 are at '

In [15]: s = 'instrument reports for wfc3 are at '
In [16]: s.upper()
Out[16]: 'INSTRUMENT REPORTS FOR WFC3 ARE AT '

```

**Comment by rayalucas** [comment]
# lcase-ucase
No stak Jupyter notebook here. Simply links to Python documentation on string methods at https://docs.python.org/3.6/library/stdtypes.html#string-methods .

**Comment by rayalucas** [comment]
# urand
No stak Jupyter notebook here. Simply links to SciPy.org documentation on numpy.random.uniform at https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.uniform.html  and  SciPy.org documentation on Random sampling at https://docs.scipy.org/doc/numpy/reference/routines.random.html .

**Comment by SaOgaz** [comment]
Hi all, I'm going to have to prioritize what additional examples I add to the notebooks as I'm running low on time, and this seems very low priority since the provided docs contain examples and these are more basic functions.  Thanks for the feedback!
