### ISSUE TITLE
gotchas notebook - and introduction to Python

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#69]
What are your gotchas going from IDL or IRAF to Python.

**Comment by jaymedina** [comment]
For UVIS WFC3 .fits files:

- Chip 2 data is in Extension 1 (`[SCI,1]`) 
- Chip 1 data is in Extension 4 (`[SCI,2]`)

**Comment by SaOgaz** [comment]
Upgrading this notebook to a full fledged Astronomy Python introduction with sections on 

- Difference between IRAF workflow and Python workflow.  Instead of running single chunks more of a stream of functions, and work with image arrays in numpy arrays.

- Section on simple examples of opening a FITS file, closing a FITS file, saving out a new edited image.  Include some brief explanations about what the Astropy classes mean (HDU, HDUList, Data array, Header object)

- Link to helpful packages, what tutorials to look at next for more background information. (Astropy, CCDProc, Scipy, matplotlib, ginga, and our Astroconda distribution)

- Improve blurb on the top of all notebooks to point to this notebook, etc

**Comment by SaOgaz** [comment]
Hi @jaymedina, I think this particular thing might be too HST specific for these notebooks. But I will make sure to address that the indexing for the extensions starts at 1 (unlike the rest of Python which is 0 indexed), and to be aware of which extensions the user is pulling out.  Thanks for the suggestion!
