### ISSUE TITLE
Functions that should have a one line wrapper

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#71]
Please provide what functions are VERY important to you that they have a wrapper written in Python.  Provide the example(s) line of how you call this task in IRAF.

**Comment by SMBaggett** [comment]
Thank you for considering making some one-liners; they could save significant time for users:
imcalc   with multi-image input, & conditional expressions
hselect
imstat/msstat
tcalc
imhistogram
imcombine/mscombine (perhaps could build on some existing code from e.g. Myles, Ben, & others) - would be very useful if it could handle very large numbers of input images
