### ISSUE TITLE
imgeom.rotate functionality

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#75]
Moving discussion of imgeom.rotate with @SMBaggett here.

**Comment by SaOgaz** [comment]
Hi @SMBaggett,
That latest example you showed, was it using the same array for the IRAF runs?  Just wanted to double check.

There's kind of an additional thing going on here as well.  The default interpolation happening in IRAF is linear.  The only options for interpolation in the scipy version are splines.  So (and I should have been more specific about this in our slack conversation) to do a true apples to apples comparison of rotates between iraf and scipy, you would need to run the IRAF version with interpolant="spline3" (the scipy version default is spline3).

Next, I looked and I could not find a linear interpolation rotation in Python.  And from what I could see, people were just writing up their own functions to do this in the wild.  But my follow up question is, is there a large need in the astronomy community for a linear interpolation rotate function? If users are mostly rotating in 90 degree chucks, then no interpolation is needed, and as in the notebook example, the ``numpy.rot90`` function can be used. 

Either way, I should add more notes to the notebook example to clarify this to users, and thanks for helping me look into this @SMBaggett!

Thoughts on this @SMBaggett and @eteq?

**Comment by SMBaggett** [comment]
@SaraOgaz @eteq 

- Yes, the examples of pyraf rotate were on a small 5x5 pixel image replicating the values in your 5x5 example array.

```
--> catfits smallimage.fits
EXT#  FITSNAME      FILENAME              EXTVE DIMENS       BITPI OBJECT
0     smallimage.fi iczgs3y5q_flt.fits          5x5          -32
--> epix smallimage.fits[0] 3 3 box=5
              1        2        3        4        5
       1       1.       2.       3.       4.       5.
       2       6.       7.       8.       9.      10.
       3      11.      12.      13.      14.      15.
       4      16.      17.      18.      19.      20.
       5      21.      22.      23.      24.      25.

```

- Good point, yes, rotate uses a linear interpolant by default. However, I've since run them with spline3 and still the image diffs are of order 10-6 to 10-7, nowhere near as high as the python rotate image diffs integer values. 

```
from pyraf
rotate smallimage.fits[0] smallimagers.fits rotation=90. interpolant=spline3
rotate smallimagers.fits[0] smallimagers2.fits rotation=90. interpolant=spline3
rotate smallimagers2.fits[0] smallimagers3.fits rotation=90. interpolant=spline3
rotate smallimagers3.fits[0] smallimagers4.fits rotation=90. interpolant=spline3
rotate smallimage.fits[0] smallimagecs.fits rotation=270 interpolant=spline3
rotate smallimage.fits[0] smallimagees.fits rotation=360 interpolant=spline3
imarith smallimagecs.fits[0] - smallimagers3.fits[0] smallimagecsminrs3.fits
imarith smallimage.fits[0] - smallimagees.fits[0] smallimagemines.fits

--> epix smallimagecsminrs3.fits 3 3 box=5                     (rotation 270 - 3*[rotation 90])
              1        2        3        4        5
       1 4.768E-7       0. 9.537E-7 1.907E-6       0.
       2       0. -1.91E-6       0.       0.       0.
       3 2.384E-7       0. 9.537E-7 -1.91E-6 -1.91E-6
       4 2.384E-7       0.       0.       0. -1.91E-6
       5 5.960E-8 -4.77E-7       0. 9.537E-7 -1.91E-6

--> epix smallimagemines.fits 3 3 box=5				(original - [rotation 360])
              1        2        3        4        5
       1       0. 1.192E-7       0.       0. -4.77E-7
       2       0. -4.77E-7 9.537E-7       0.       0.
       3       0.       0. 9.537E-7       0.       0.
       4       0.       0.       0.       0.       0.
       5 -1.91E-6       0.       0.       0.       0.

```
Thank *you* for setting up these notebooks; they and the testing have been a useful learning experience!
