### ISSUE TITLE
INS Review: Introduction notebook

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#80]

**Comment by SaOgaz** [comment]
Add one more example to FITS I/O, of saving out a clean new array to a clean new file.

**Comment by tddesjardins** [comment]
I like what I see here. I just noticed a couple typos:

**Workflow Philosophy**

1. Second paragraph: oftentimes is one word, not two.
2. Third paragraph: “is the Jupyter Notebooks.” -> “is the Jupyter Notebook.”

**FITS File I/O**

1. Second paragraph: “and it’s associated header” -> “and its associated header” (happens twice)

**Comment by SMBaggett** [comment]
Thanks for developing the Introduction; it should prove extremely useful to new python users. 

A  few minor typos:
 it’s screen output   (needs to be its)
 avaialbe
 both index arrays both start a   (extra 'both')

Really like the Gotcha section and the Links.
Might add the comment on necessity of doing close after a writeto into the Gotchas as well.

And a question re: write section: is a close still needed on e.g. the new fits file ('acsdata_new.fits' in example)? If not, could be useful to state that. The new fits file seemed to already exist ok without a close.

**Comment by SaOgaz** [comment]
Hi @SMBaggett, it does close the file for you, I've added that to the notes (along with you're other changes). Thanks!

**Comment by SMBaggett** [comment]
@SaraOgaz Thank you; the intro was a good idea!
